extends:
  - prettier
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended

parser: "@babel/eslint-parser"

parserOptions:
  ecmaVersion: 2021
  ecmaFeatures:
    jsx: true

env:
  node: true
  browser: true
  jest: true

plugins:
  - prettier
  - jest
  - react
  - jsx-a11y

rules:
  no-unused-vars: error
  react/prop-types: 0
  no-tabs: 0
  no-async-promise-executor:
    - "off"
  no-empty-pattern:
    - "off"
  no-undef:
    - error
  no-var:
    - error
  curly:
    - error
    - multi
  object-curly-spacing:
    - error
    - always
  quotes:
    - error
    - double
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  spaced-comment:
    - "off"
  no-prototype-builtins:
    - "off"
  sort-keys:
    - "off"
  space-before-function-paren:
    - "off"
  indent:
    - "off"
  prefer-const:
    - error
    - destructuring: any
      ignoreReadBeforeAssign: false
  prefer-destructuring:
    - error
    - array: true
      object: true
    - enforceForRenamedProperties: false
  space-unary-ops:
    - 2
    - words: true
      nonwords: false
      overrides:
        new: true
        "=": true
